left_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - linear_joint
    - left_shoulder_pan_joint
    - left_shoulder_lift_joint
    - left_elbow_joint
    - left_wrist_1_joint
    - left_wrist_2_joint
    - left_wrist_3_joint
  gains:
    linear_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1