controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: fake_torso_controller
    type: $(arg fake_execution_type)
    joints:
      - linear_joint
  - name: fake_left_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_gripper_finger1_joint
  - name: fake_right_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - right_gripper_finger1_joint
  - name: fake_head_controller
    type: $(arg fake_execution_type)
    joints:
      - pan_joint
      - tilt_joint
  - name: fake_right_side_controller
    type: $(arg fake_execution_type)
    joints:
      - linear_joint
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: fake_left_side_controller
    type: $(arg fake_execution_type)
    joints:
      - linear_joint
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: fake_upper_body_controller
    type: $(arg fake_execution_type)
    joints:
      - linear_joint
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - pan_joint
      - tilt_joint
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: fake_whole_body_left_controller
    type: $(arg fake_execution_type)
    joints:
      - linear_joint
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - left_gripper_finger1_joint
initial:  # Define initial robot poses per group
  - group: left_arm
    pose: tucked_left_arm
  - group: right_arm
    pose: tucked_right_arm
  - group: torso
    pose: tucked_torso
  - group: upper_body
    pose: homed